# docker build -f dockerfile_fusionseeker -t shahcompbio/fusionseeker . |& tee build_fusionseeker.log
# docker push shahcompbio/fusionseeker

FROM ubuntu:20.04
ENV PATH="/fusionseeker/miniconda3/bin:/bsalign:/FusionSeeker:${PATH}"
ARG PATH="/fusionseeker/miniconda3/bin:/bsalign:/FusionSeeker:${PATH}"
RUN apt-get update

RUN apt-get install -y wget git build-essential

RUN wget \
    https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh \
    && mkdir -p /fusionseeker/.conda \
    && bash Miniconda3-latest-Linux-x86_64.sh -p /fusionseeker/miniconda3 -b \
    && rm -f Miniconda3-latest-Linux-x86_64.sh 

RUN conda config --add channels bioconda
RUN conda config --add channels conda-forge
RUN conda install -y minimap2 pysam samtools

RUN apt-get install -y zlib1g-dev
RUN git clone https://github.com/ruanjue/bsalign.git && cd /bsalign && make
RUN git clone https://github.com/Maggi-Chen/FusionSeeker.git
